package infer

import (
	"encoding/xml"
	"fmt"
	"strconv"
	"strings"

	"github.com/chriswirz/xsd2code-go/internal/ir"
)

// XSD renders the inferred structure as a schema document.
func (s *Schema) XSD() string {
	target := s.targetNamespace()
	for _, ns := range s.otherNamespaces() {
		s.warn("elements in namespace %q are described without their namespace: one schema document declares one target namespace", ns)
	}

	names := s.typeNames()
	b := &writer{pad: "  "}

	b.line(`<?xml version="1.0" encoding="UTF-8"?>`)
	b.line(`<!--`)
	b.line(`  Generated by xsd2code-go from %d sample document%s.`, s.docs, plural(s.docs))
	b.line(`  It describes the samples, not the format: anything the samples never`)
	b.line(`  showed is absent, and every optional/repeated decision below is a count`)
	b.line(`  taken over the input. Review it before treating it as a contract.`)
	for _, w := range s.Warnings {
		b.line(`  Note: %s`, escape(w))
	}
	b.line(`-->`)

	attrs := []string{`xmlns:xs="http://www.w3.org/2001/XMLSchema"`}
	if target != "" {
		attrs = append(attrs,
			`targetNamespace=`+attrv(target),
			`xmlns:tns=`+attrv(target),
			`elementFormDefault="qualified"`)
	}
	b.line(`<xs:schema %s>`, strings.Join(attrs, " "))
	b.in()

	// Roots first: a reader looks for the document element before anything
	// else, and so does every tool that validates against the result.
	for _, root := range s.roots {
		b.line("")
		b.line(`<xs:element name=%s type=%s/>`, attrv(root.Local), attrv(s.qualify(names[root], target)))
	}

	for _, name := range s.order {
		el := s.elements[name]
		b.line("")
		if isLeaf(el) {
			s.emitSimple(b, el, names[name], target)
			continue
		}
		s.emitComplex(b, el, names[name], target)
	}

	b.out()
	b.line(`</xs:schema>`)
	return b.String()
}

// isLeaf reports whether an element has neither children nor attributes, and
// so needs a simple type rather than a complex one.
func isLeaf(el *Element) bool {
	return len(el.Children) == 0 && len(el.Attrs) == 0
}

// emitSimple writes the named simple type for a leaf element: an enumeration
// when the values look like one, and a plain restriction otherwise. A named
// type is emitted even when it is a bare alias of a built-in, so that every
// element in the schema is described in one place.
func (s *Schema) emitSimple(b *writer, el *Element, name, target string) {
	base := "xs:" + el.Text.Type(s.opts.Strings)
	values := el.Text.Enum(s.opts)

	b.line(`<xs:simpleType name=%s>`, attrv(name))
	b.in()
	s.annotate(b, fmt.Sprintf("Seen %d time%s.", el.Instances, plural(el.Instances)))
	if len(values) == 0 {
		// No enumeration to constrain it: the restriction is a bare alias, so
		// it is written as an empty element rather than an empty block.
		b.line(`<xs:restriction base=%s/>`, attrv(base))
	} else {
		b.line(`<xs:restriction base=%s>`, attrv(base))
		b.in()
		for _, v := range values {
			b.line(`<xs:enumeration value=%s/>`, attrv(v))
		}
		b.out()
		b.line(`</xs:restriction>`)
	}
	b.out()
	b.line(`</xs:simpleType>`)
}

// emitComplex writes the named complex type for an element with structure.
func (s *Schema) emitComplex(b *writer, el *Element, name, target string) {
	names := s.typeNames()
	hasChildren := len(el.Children) > 0
	hasText := el.TextInstances > 0

	mixed := ""
	if hasChildren && hasText {
		// Text alongside elements is mixed content. It is unusual in data
		// documents and usually means the samples contain prose.
		mixed = ` mixed="true"`
		s.warn("element %q carries text alongside its children; it is described as mixed content", el.Name.Local)
	}
	b.line(`<xs:complexType name=%s%s>`, attrv(name), mixed)
	b.in()
	s.annotate(b, fmt.Sprintf("Seen %d time%s.", el.Instances, plural(el.Instances)))

	switch {
	case hasChildren:
		compositor := "xs:sequence"
		suffix := ""
		if el.OrderVaries {
			// The samples disagreed about order, so a sequence would reject
			// documents already known to be valid. A repeated choice accepts
			// any interleaving, at the cost of no longer constraining order.
			compositor = "xs:choice"
			suffix = ` maxOccurs="unbounded"`
			s.warn("children of %q appear in varying orders; they are described as a repeated xs:choice", el.Name.Local)
		}
		b.line(`<%s%s>`, compositor, suffix)
		b.in()
		for _, childName := range el.ChildOrder {
			c := el.Children[childName]
			occurs := occursAttrs(c, el.Instances, el.OrderVaries)
			b.line(`<xs:element name=%s type=%s%s/>`,
				attrv(childName.Local), attrv(s.qualify(names[childName], target)), occurs)
		}
		b.out()
		b.line(`</%s>`, compositor)
		s.emitAttributes(b, el)
	case hasText:
		// Text plus attributes is simple content: a value with metadata on it.
		b.line(`<xs:simpleContent>`)
		b.in()
		b.line(`<xs:extension base="xs:%s">`, el.Text.Type(s.opts.Strings))
		b.in()
		s.emitAttributes(b, el)
		b.out()
		b.line(`</xs:extension>`)
		b.out()
		b.line(`</xs:simpleContent>`)
	default:
		// Attributes only: an element that carries no content at all.
		s.emitAttributes(b, el)
	}

	b.out()
	b.line(`</xs:complexType>`)
}

// emitAttributes writes the attribute declarations of an element.
func (s *Schema) emitAttributes(b *writer, el *Element) {
	for _, name := range el.AttrOrder {
		at := el.Attrs[name]
		use := ""
		if at.Count == el.Instances {
			// Present on every occurrence seen. That is evidence, not proof,
			// which is what the schema-level annotation warns about.
			use = ` use="required"`
		}
		values := at.Values.Enum(s.opts)
		local := name.Local
		if len(values) == 0 {
			b.line(`<xs:attribute name=%s type="xs:%s"%s/>`, attrv(local), at.Values.Type(s.opts.Strings), use)
			continue
		}
		b.line(`<xs:attribute name=%s%s>`, attrv(local), use)
		b.in()
		b.line(`<xs:simpleType>`)
		b.in()
		b.line(`<xs:restriction base="xs:%s">`, at.Values.Type(s.opts.Strings))
		b.in()
		for _, v := range values {
			b.line(`<xs:enumeration value=%s/>`, attrv(v))
		}
		b.out()
		b.line(`</xs:restriction>`)
		b.out()
		b.line(`</xs:simpleType>`)
		b.out()
		b.line(`</xs:attribute>`)
	}
}

// annotate writes an xs:documentation block.
func (s *Schema) annotate(b *writer, text string) {
	b.line(`<xs:annotation>`)
	b.in()
	b.line(`<xs:documentation>%s</xs:documentation>`, escape(text))
	b.out()
	b.line(`</xs:annotation>`)
}

// occursAttrs renders minOccurs and maxOccurs for a child.
//
// A child seen in every parent is required; one seen in some is optional. When
// the parent's children are described as a repeated choice the per-child
// minimum has to be 0, because a choice can only ever match one of them.
func occursAttrs(c *Child, parentInstances int, inChoice bool) string {
	var parts []string
	if inChoice || c.ParentsWith < parentInstances {
		parts = append(parts, `minOccurs="0"`)
	}
	switch {
	case inChoice:
		// The enclosing choice already carries maxOccurs="unbounded".
	case c.MaxPerParent > 1:
		parts = append(parts, `maxOccurs="unbounded"`)
	}
	if len(parts) == 0 {
		return ""
	}
	return " " + strings.Join(parts, " ")
}

// typeNames assigns a unique type name to every element, derived from the
// element's own name. The result is memoized so that every reference to an
// element resolves to the same type name.
func (s *Schema) typeNames() map[xml.Name]string {
	if s.names != nil {
		return s.names
	}
	taken := map[string]bool{}
	out := map[xml.Name]string{}
	for _, name := range s.order {
		base := ir.Pascal(name.Local) + "Type"
		candidate := base
		for i := 2; taken[candidate]; i++ {
			candidate = base + strconv.Itoa(i)
		}
		taken[candidate] = true
		out[name] = candidate
	}
	s.names = out
	return out
}

// qualify prefixes a type name with the target namespace's prefix.
func (s *Schema) qualify(name, target string) string {
	if target == "" {
		return name
	}
	return "tns:" + name
}

// writer is a tiny indent-aware text writer for the schema document.
type writer struct {
	sb    strings.Builder
	depth int
	pad   string
}

func (w *writer) in()  { w.depth++ }
func (w *writer) out() { w.depth-- }

func (w *writer) line(format string, args ...any) {
	if format != "" {
		w.sb.WriteString(strings.Repeat(w.pad, w.depth))
		if len(args) == 0 {
			w.sb.WriteString(format)
		} else {
			fmt.Fprintf(&w.sb, format, args...)
		}
	}
	w.sb.WriteString("\n")
}

func (w *writer) String() string { return w.sb.String() }

// escape makes text safe as XML character data or as an attribute value.
func escape(s string) string {
	var b strings.Builder
	xml.EscapeText(&b, []byte(s))
	return b.String()
}

// attrv renders a value as a quoted, XML-escaped attribute value. Go's %q
// would escape it for Go rather than for XML.
func attrv(s string) string { return `"` + escape(s) + `"` }

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
